# Generated by Django 5.1.2 on 2024-11-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book_Store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=1000),
        ),
    ]
