# Generated by Django 5.1.2 on 2024-12-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book_Store", "0002_alter_author_first_name_alter_author_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description_short",
            field=models.TextField(blank=True),
        ),
    ]
