# Generated by Django 5.1.2 on 2024-12-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book_Store", "0003_book_description_short"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fiction", "Fiction"),
                    ("nonfiction", "Non-Fiction"),
                    ("mystery", "Mystery"),
                    ("fantasy", "Fantasy"),
                    ("biography", "Biography"),
                    ("science", "Science"),
                    ("history", "History"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
