# Generated by Django 5.1.2 on 2024-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book_Store", "0004_book_category_book_published_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AddField(
            model_name="book",
            name="bookID",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
