# Generated by Django 5.1.2 on 2024-12-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book_Store", "0005_remove_book_id_book_bookid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="bookID",
        ),
        migrations.AddField(
            model_name="book",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
